
services:
  db:
    image: postgres:15.11-alpine3.21
    container_name: postgres
    env_file:
      db_env.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # first port is the outside port
    networks:
      - common_network

  backend:
    build: ./backend
    container_name: flaskapp
    env_file:
      - backend_env.env
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart:
      "on-failure:1"
    volumes:
      - ./backend:/app
    networks:
      - common_network

  frontend:
    build: ./frontend
    container_name: flaskapp_frontend
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend
    networks:
      - common_network

volumes:
  postgres_data:

networks:
  common_network:
    driver: bridge